export enum BUTTON_ACTIONS {
  NAVIGATE_TO_HOME_SCREEN = "NAVIGATE_TO_HOME_SCREEN",
  NAVIGATE_TO_PROFILE_SCREEN = "NAVIGATE_TO_PROFILE_SCREEN",
  NAVIGATE_TO_SETTINGS_SCREEN = "NAVIGATE_TO_SETTINGS_SCREEN",
}
