export enum BUTTON_ACTIONS {
  NAVIGATE_TO_HOME_SCREEN = "NAVIGATE_TO_HOME_SCREEN",
  NAVIGATE_TO_PROFILE_SCREEN = "NAVIGATE_TO_PROFILE_SCREEN",
  NAVIGATE_TO_SETTINGS_SCREEN = "NAVIGATE_TO_SETTINGS_SCREEN",
  NAVIGATE_TO_FAQ_SCREEN = "NAVIGATE_TO_FAQ_SCREEN",
  TOGGLE_SOUNDS = "TOGGLE_SOUNDS",
  TOGGLE_MUSIC = "TOGGLE_MUSIC",
  OPEN_SHARE_MODAL = "OPEN_SHARE_MODAL",
  OPEN_GOOGLE_STORE = "OPEN_GOOGLE_STORE",
  RATE_APP = "RATE_APP",
}
