export const GRAPHICS = {
  BUTTONS: {
    ROUND: require("../../assets/buttons/b3.png"),
    FLAT: require("../../assets/buttons/b2.png"),
    FLAT_DOUBLE: require("../../assets/buttons/b6.png"),
    EMPTY: require("../../assets/icons/empty.png"),
    PICKER_LEFT: require("../../assets/buttons/b4.png"),
    PICKER_RIGHT: require("../../assets/buttons/b5.png"),
  },
  ICONS: {
    SETTINGS: require("../../assets/icons/003-settings.png"),
    AVATAR: require("../../assets/icons/057-avatar.png"),
    SHARE: require("../../assets/icons/024-share.png"),
    LIKE_US: require("../../assets/icons/044-like.png"),
    QUESTION: require("../../assets/icons/question-mark-draw.png"),
    STORE: require("../../assets/icons/037-store.png"),
    BACK_SCREEN_ARROW: require("../../assets/icons/back-screen-arrow.png"),
    EMPTY: require("../../assets/icons/empty.png"),
    MUSIC_ON: require("../../assets/icons/music-on.png"),
    MUSIC_OFF: require("../../assets/icons/music-off.png"),
    SOUNDS_OFF: require("../../assets/icons/sounds-off.png"),
    SOUNDS_ON: require("../../assets/icons/sounds-on.png"),
  },
  FIELDS: {
    PICKER_SHORT: require("../../assets/fields/f2.png"),
    PICKER_LONG: require("../../assets/fields/f1.png"),
    TYPING_LIGHT: require("../../assets/fields/f3.png"),
    TYPING_DARK: require("../../assets/fields/f4.png"),
  },
};
